"""Initial database schema

Revision ID: 223eae63f89f
Revises: 
Create Date: 2025-04-02 03:29:46.011951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '223eae63f89f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('scrape_quota', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.drop_table('payments')
    op.drop_table('products')
    op.drop_table('analyses')
    op.drop_table('prompts')
    op.drop_table('launch_plans')
    op.drop_table('system_settings')
    op.add_column('projects', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('owner_id', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'user_id')
    op.drop_column('projects', 'project_type')
    op.drop_column('projects', 'analysis_status')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'analysis_completed_at')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', name='userstatus'), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('scrape_quota', sa.Integer(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'name')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'tier')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'trial_expires_at')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('trial_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('users', 'scrape_quota')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('projects', sa.Column('analysis_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('analysis_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('project_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('projects', 'is_active')
    op.drop_column('projects', 'owner_id')
    op.drop_column('projects', 'subcategory')
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('max_crawl_images', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_products_per_project', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saas_accounts_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stripe_public_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stripe_secret_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_prompts_enabled', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('max_free_tier_projects', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_basic_tier_projects', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_premium_tier_projects', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allow_public_signup', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('google_auth_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey')
    )
    op.create_table('launch_plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='launch_plans_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='launch_plans_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='launch_plans_pkey')
    )
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='prompts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prompts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('analysis_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prompt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='analyses_product_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='analyses_project_id_fkey'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name='analyses_prompt_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='analyses_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analyses_pkey')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('is_target_product', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scraped_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='products_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='products_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subscription_tier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
